version: '2'
services:



  #mongodb service
  search-mongo:
    container_name: search-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-vol:/data/db
    networks:
      - search-network


volumes:
  mongo-vol:
    driver: local


networks:
  search-network:
    driver: bridge
    #    external: true

